"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

import os
from re import X

import ldap
from django_auth_ldap.config import LDAPSearch, NestedGroupOfNamesType

#Definindo o Servidor LDAP
AUTH_LDAP_SERVER_URI = 'ldap://%s' % os.environ["LDAP_SERVER"]

#Definindo o usuário e a pesquisa para esse usuário, fazer o BIND
AUTH_LDAP_BIND_DN = os.environ["LDAP_BIND_DN"]
AUTH_LDAP_BIND_PASSWORD = os.environ["LDAP_BIND_PASSWORD"]
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "cn=users,dc=htbnoc,dc=com", ldap.SCOPE_SUBTREE, "(cn=%(user)s)"
)

#Definindo o metodo de busca dos grupos
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
            "CN=Builtin,dc=htbnoc,dc=com", 
            ldap.SCOPE_SUBTREE,
             "(objectClass=group)",
            )
AUTH_LDAP_GROUP_TYPE = NestedGroupOfNamesType()

#Popular o Django com usuários do AD.
AUTH_LDAP_USER_ATTR_MAP = {
            "username": "cn",
            "first_name": "givenName",
            "last_name": "sn",
             "email": "mail",
}

#AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType(name_attr="cn")
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
            "is_active" : ["CN=Eng-Full,CN=Builtin,DC=htbnoc,DC=com", "CN=Eng-View,CN=Builtin,DC=htbnoc,DC=com"],
            "is_superuser": "CN=Eng-Full,CN=Builtin,DC=htbnoc,DC=com",
            "is_staff": "CN=Eng-Full,CN=Builtin,DC=htbnoc,DC=com",
}

#Forçar atualizar os usuários
AUTH_LDAP_ALWAYS_UPDATE_USER = True

#Usar os grupos do AD para verificar as permissoes
AUTH_LDAP_FIND_GROUP_PERMS = True

#Manter cache de usuários para diminuir pesquisas no AD.
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600

# Manter os servidores de autenticação Remoto, e depois local.
AUTHENTICATION_BACKENDS = [
            'django_auth_ldap.backend.LDAPBackend',
                'django.contrib.auth.backends.ModelBackend',
]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = os.environ["SECRET_KEY"]
except KeyError as e:
    raise RuntimeError("Chave nao encontrada!") from e

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webcontrolurl',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),] 

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = "/var/www/webcontrolurl/static"

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'